" defaults write com.sublimetext.3 ApplePressAndHoldEnabled -bool false
" export PHANTOMJS_BIN=/path/to/node_modules/karma-phantomjs-launcher/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs


" autocmd Filetype html setlocal ts=6 sts=2 sw=2
" autocmd Filetype ruby setlocal ts=2 sts=2 sw=2
" autocmd Filetype javascript setlocal ts=4 sts=4 sw=4

set number
set relativenumber " use relative line numbers
set showcmd        " feedback showing <leader> key is pressed
set encoding=utf-8
set nocompatible   " disable vi compatibility as required by vundle
set laststatus=2
set background=dark
set t_Co=256
set cursorline
set tabstop=2 softtabstop=2 shiftwidth=2
set expandtab autoindent smarttab
set backspace=indent,eol,start " allow backspace when no text entered in insert session

let g:solarized_termcolors=256
let mapleader = "," " map <Leader> to , 

syntax enable

" Vundle config
filetype off
call plug#begin('~/.vim/bundle')
Plug 'junegunn/fzf', { 'dir': '~/.vim/bundle/fzf', 'do': './install --all' }
Plug 'gmarik/vundle'
Plug 'altercation/vim-colors-solarized'
Plug 'scrooloose/nerdtree', { 'on': ['NERDTreeToggle', 'NERDTreeFind'] }
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-fugitive'
Plug 'christoomey/vim-tmux-navigator'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-scripts/localvimrc'
" Plug 'Raimondi/delimitMate'
Plug 'pangloss/vim-javascript', { 'for': ['javascript', 'javascript.eruby'] }
call plug#end()
filetype plugin indent on

colorscheme solarized

" NERDTree
nnoremap <silent> <c-d> :NERDTreeToggle<cr>
nnoremap <leader>t :NERDTreeFind<cr>

" FZF 
nnoremap <silent> <c-p> :FZF<cr>

"" Nop arrow keys
noremap <up> <nop>
noremap <right> <nop>
noremap <down> <nop>
noremap <left> <nop>
inoremap <up> <nop>
inoremap <right> <nop>
inoremap <down> <nop>
inoremap <left> <nop>

"" delimitMate
imap <C-c> <CR><Esc>O

" airline
let g:airline_powerline_fonts=1
let g:airline_section_z=airline#section#create_right(["l/%L"])
let g:airline_theme="badwolf"

vmap <C-x> :!pbcopy<CR>  
vmap <C-c> :w !pbcopy<CR><CR>

" Syntastic
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
nnoremap <leader>sc :SyntasticCheck<cr>
let g:syntastic_javascript_checkers = ["jshint", "eslint", "jsxhint"]
let g:syntastic_html_tidy_ignore_errors = [" proprietary attribute \"ng-"]

" Search
:set hlsearch
:set incsearch

" Whitespace

"" List chars
set listchars=""
set listchars=tab:>>
set listchars+=trail:-
set listchars+=extends:>
set list
